version: '3'

services:
  webapp:
    build:
      context: ./client/web
      dockerfile: Dockerfile
      args:
          # The reason why we need to use localhost here instead of 'webapi'
          # is because the react app is served from a container as a js script file to the browser.
          # And since the browser is the one sending the requests to the backend,
          # (and the browser is by any means not inside the docker network), the outer port (and host) mapping must be used
          # to reach the backend.
        - REACT_APP_DIRMOD_API_DOMAIN=http://localhost:5050/api/v1/
    image: dirmod-webapp
    ports:
      - "3030:80"
    depends_on:
      - webapi
    networks:
      - dirmodnet

  webapi:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    image: dirmod-webapi
    environment:
      - DIRMODAPI_CAMBIOTODAY__KEY=${CAMBIOTODAY_KEY}
    ports:
      - "5050:5050"
    networks:
      - dirmodnet

# This networks section isn't necessary for the complexity of this project.
# Compose sets up a single network and each container service joins this network by default (unless specified otherwise).
# But, since I like to be as explicit as I can, I'm going to leave it here. :) 
networks:
  dirmodnet:
    driver: "bridge"
