apiVersion: skaffold/v1
kind: Config
metadata:
  name: dirmodpoc
build:
  artifacts:
  - image: germmand/dirmodapi
    context: api-server
deploy:
  helm:
    releases:
      - name: dirmodapiservice-chart
        chartPath: chart/dirmodapp/charts/dirmodapiservice
        values:
          image: germmand/dirmodapi
