apiVersion: skaffold/v1
kind: Config
metadata:
  name: dirmodpoc
build:
  artifacts:
  - image: germmand/dirmodapi
    context: api-server
  - image: germmand/dirmodwebapp
    context: client/web
deploy:
  helm:
    releases:
      - name: dirmodapiservice-chart
        chartPath: chart/dirmodapp/charts/dirmodapiservice
        values:
          image: germmand/dirmodapi
      - name: frontendservice-chart
        chartPath: chart/dirmodapp/charts/frontendservice
        values:
          image: germmand/dirmodwebapp
