apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: dirmodapp
version: 0.1.0
dependencies:
  - name: dirmodapiservice
    repository: file://charts/dirmodapiservice
  - name: frontendservice
    repository: file://charts/frontendservice
